//! Lawyer cron-schedule reference page as a Dioxus component (#956 Phase 4).
//!
//! The successor to the `views::pages::admin::schedules`. Lists the
//! Kubernetes `CronJob`s that drive Neon Law Navigator's scheduled work with
//! their cron expression, a human cadence, what each does, and — where the job
//! can be started on demand — a "Run now" trigger.
//!
//! This is a *declared* reference, not a live cluster read (`web` has no
//! Kubernetes API access). What it declares is the deployment render:
//! [`RENDERED_CRON_JOBS`] is generated by `webapp/build.rs` from the
//! `resources:` list in `examples/deploy/k8s/exports/kustomization.yaml` — the
//! same list `kubectl kustomize` resolves when `ops ship` reconciles the
//! cluster. A job appears here because it ships, not because someone remembered
//! to add a row.
//!
//! Only the operator-facing prose is written by hand, in [`JOB_COPY`], keyed by
//! the `CronJob`'s `metadata.name`. A rendered job with no entry there still
//! gets a row carrying its real name and schedule, so the page can never be
//! shorter than the render; the missing prose is a test failure rather than an
//! omission the reader has to notice.
//!
//! `POST /app/admin/schedules/{job}/run` stays on the `portal::cron_schedules`
//! handler and already follows post/redirect/get: it redirects back here with
//! `?notice=queued:{slug}` (or `not_queued`), which renders as a toast.

use dioxus::prelude::*;
use serde::{Deserialize, Serialize};

use crate::components::{Column, DataTable, SortState, Toast, ToastTone};
use crate::people::ViewerRole;

/// The page's own path, and the base the "Run now" forms post under.
pub const SCHEDULES_PATH: &str = "/app/admin/schedules";

/// One `CronJob` the deployment render ships.
///
/// `webapp/build.rs` reads these out of the manifests named by
/// `examples/deploy/k8s/exports/kustomization.yaml`'s `resources:` list, so the
/// set is whatever `ops ship` applies.
pub struct RenderedCronJob {
    /// The `CronJob`'s `metadata.name`.
    pub name: &'static str,
    /// `spec.schedule` — the cron expression (UTC), exactly as deployed.
    pub schedule: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/rendered_cron_jobs.rs"));

/// Operator-facing prose for one shipped `CronJob`, keyed by its
/// `metadata.name`.
///
/// A manifest carries no display name, no Pacific cadence, and no account of
/// what the job is for, so that copy is written here. What this table
/// deliberately does *not* carry is the cron expression or the job's presence:
/// both come from the render, which is why it cannot put a job on the page that
/// no cluster runs.
struct JobCopy {
    /// The `CronJob`'s `metadata.name`, joining this copy to the render.
    cron_name: &'static str,
    /// Display name.
    name: &'static str,
    /// Human cadence, in the workspace's Pacific convention.
    cadence: &'static str,
    /// What the job does.
    description: &'static str,
    /// The `POST` route segment that queues this job on demand, for the jobs
    /// `portal::cron_schedules` can start. `None` where there is no such route:
    /// a self-contained batch has no durable workflow for the Restate ingress
    /// to invoke, and a button that answers 404 is worse than no button.
    manual_slug: Option<&'static str>,
}

const JOB_COPY: &[JobCopy] = &[
    JobCopy {
        cron_name: "archives-trigger",
        name: "Archives nightly export",
        cadence: "Daily · 02:00 PST",
        description: "Snapshots every database table to Parquet on GCS, summarizes GCP cost, \
                      and emails the diagnostic report.",
        manual_slug: Some("archives"),
    },
    JobCopy {
        cron_name: "surreal-archive",
        name: "SurrealDB operational archive",
        cadence: "Daily · 03:00 PST",
        description: "Exports the database to a recoverable SurrealQL artifact on object \
                      storage — the operational restore path, distinct from the analytical \
                      Parquet output the nightly Archives workflow writes.",
        manual_slug: None,
    },
    JobCopy {
        cron_name: "billing-digest-trigger",
        name: "Billing digest",
        cadence: "Daily · 05:00 PST",
        description: "Posts firm ops a trailing-30-day GCP cost report covering every configured \
                      billing account and every project on each — a cross-account roll-up, then \
                      per account a table by project and one by service, each against the prior \
                      30 days. A two-step Restate workflow; a no-op where no billing export is \
                      configured.",
        manual_slug: Some("billing-digest"),
    },
    JobCopy {
        cron_name: "dri-digest-trigger",
        name: "DRI digest",
        cadence: "Daily · 17:11 PST (prior day)",
        description: "Reads every project's lawyer and client DRI and posts firm ops one Slack \
                      line per project naming both sides, saying \"none\" where a side is \
                      unassigned so the gap is visible from the notice itself.",
        manual_slug: None,
    },
    JobCopy {
        cron_name: "general-nag",
        name: "General channel nag",
        cadence: "Daily · 17:11 PST (prior day)",
        description: "Posts one static daily message to the firm's general Slack channel through \
                      the Web API and exits — a self-contained batch with no durable workflow \
                      behind it.",
        manual_slug: None,
    },
    JobCopy {
        cron_name: "heartbeat-trigger",
        name: "Durable-execution heartbeat",
        cadence: "Every 6h · 00/06/12/18 UTC",
        description: "Liveness canary for the durable-execution engine itself — a two-step \
                      Restate workflow (beat → notify) that depends on nothing (no database, \
                      no object storage, no third-party API), so a green run can only mean the \
                      engine accepted an invocation and ran it to completion. Emails firm ops \
                      every six hours with the Restate Cloud + GCP console links to check when \
                      a beat is missing.",
        manual_slug: Some("heartbeat"),
    },
    JobCopy {
        cron_name: "github-automation-heartbeat-trigger",
        name: "GitHub-automation authority canary",
        cadence: "Every 6h · 00/06/12/18 UTC",
        description: "Liveness canary for the GitHub-automation authority — a body-free \
                      two-step Restate workflow that journals a beat and sends the one-line \
                      authority notice through the ops notifier. It never receives a webhook, \
                      reads repository content, mints a GitHub token, or invokes an agent.",
        manual_slug: None,
    },
];

/// The prose shown for a rendered `CronJob` nobody has described yet. The row
/// still carries the job's real name and schedule, so the page stays complete;
/// `every_rendered_cron_job_carries_operator_copy` fails until someone writes
/// the description.
const UNDOCUMENTED: &str = "No description written for this job yet.";

/// One scheduled job, as the page needs it: the render's facts joined to the
/// hand-written prose.
pub struct CronJobEntry {
    /// Display name. Where the job has a manual route, this must match the name
    /// `portal::cron_schedules` knows for that slug, because it is what the
    /// redirect notice names back.
    pub name: &'static str,
    /// Cron expression (UTC), exactly as deployed.
    pub schedule: &'static str,
    /// Human cadence, in the workspace's Pacific convention.
    pub cadence: &'static str,
    /// What the job does.
    pub description: &'static str,
    /// The job's slug — both the `POST` route segment and the key the
    /// `?notice=` flash names — for the jobs that can be run on demand.
    pub slug: Option<&'static str>,
}

impl CronJobEntry {
    /// The `POST` route that queues this job on demand, where there is one.
    #[must_use]
    pub fn manual_run(&self) -> Option<String> {
        self.slug.map(|slug| format!("{SCHEDULES_PATH}/{slug}/run"))
    }
}

/// The `CronJob`s Neon Law Navigator ships, in display order.
///
/// Derived from the deployment render — see [`RENDERED_CRON_JOBS`]. To put a
/// row on this page, add the manifest to
/// `examples/deploy/k8s/exports/kustomization.yaml`'s `resources:` list; then
/// describe it in [`JOB_COPY`].
#[must_use]
pub fn cron_jobs() -> Vec<CronJobEntry> {
    let mut jobs: Vec<CronJobEntry> = RENDERED_CRON_JOBS
        .iter()
        .map(|rendered| {
            let copy = JOB_COPY.iter().find(|copy| copy.cron_name == rendered.name);
            CronJobEntry {
                name: copy.map_or(rendered.name, |copy| copy.name),
                schedule: rendered.schedule,
                cadence: copy.map_or(rendered.schedule, |copy| copy.cadence),
                description: copy.map_or(UNDOCUMENTED, |copy| copy.description),
                slug: copy.and_then(|copy| copy.manual_slug),
            }
        })
        .collect();
    jobs.sort_by_key(|job| job.name);
    jobs
}

/// The flash a manual run redirects back with, already resolved to a message.
#[derive(Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct ScheduleNotice {
    /// The rendered sentence, e.g. `Archives nightly export queued.`
    pub message: String,
    /// Whether the job was queued — selects the toast tone.
    pub queued: bool,
}

/// Resolve a `?notice=` value to its flash.
///
/// The value is `{outcome}:{slug}`, written by `portal::cron_schedules`'s
/// redirect. An unknown outcome or slug resolves to `None` rather than
/// rendering attacker-supplied text, so the query cannot inject a message.
#[must_use]
pub fn resolve_notice(value: Option<&str>) -> Option<ScheduleNotice> {
    let (outcome, slug) = value?.split_once(':')?;
    let jobs = cron_jobs();
    let job = jobs.iter().find(|job| job.slug == Some(slug))?;
    match outcome {
        "queued" => Some(ScheduleNotice {
            message: format!("{} queued.", job.name),
            queued: true,
        }),
        "not_queued" => Some(ScheduleNotice {
            message: format!("{} could not be queued.", job.name),
            queued: false,
        }),
        _ => None,
    }
}

/// The rendered schedules page: the session CSRF token the "Run now" forms
/// carry, the viewer's tier, and the resolved `?notice=` flash.
#[derive(Serialize, Deserialize, Clone, PartialEq, Eq, Default)]
pub struct SchedulesView {
    /// The resolved brand's tokens stylesheet href, so the page wears
    /// its own palette rather than the firm's on a non-default host.
    #[serde(default)]
    pub tokens_href: String,
    pub csrf_token: String,
    pub role: ViewerRole,
    #[serde(default)]
    pub notice: Option<ScheduleNotice>,
    /// The deploy's firm name, for the document title. Resolved from the
    /// request-scoped branding rather than written into the copy, so a
    /// white-label deploy's tab reads its own name.
    #[serde(default)]
    pub firm_name: String,
}

/// The `?notice=` flash a manual run redirects back with.
#[derive(Deserialize, Default)]
pub struct SchedulePageQuery {
    #[serde(default)]
    pub notice: Option<String>,
}

/// Load the schedules page: refuse non-lawyer, then read the CSRF token and the
/// `?notice=` flash. The job list itself is derived from the deployment render.
#[server]
pub async fn get_schedules() -> Result<SchedulesView, ServerFnError> {
    let role = crate::admin_listing::require_lawyer().await?;

    let csrf_token = dioxus_fullstack_core::FullstackContext::extract::<
        axum::Extension<crate::csrf::CsrfToken>,
        _,
    >()
    .await
    .map(|axum::Extension(token)| token.0)
    .unwrap_or_default();

    let axum::extract::Query(query) = dioxus_fullstack_core::FullstackContext::extract::<
        axum::extract::Query<SchedulePageQuery>,
        _,
    >()
    .await?;

    Ok(SchedulesView {
        tokens_href: crate::app_chrome::app_tokens_href_from_context().await,
        firm_name: crate::app_chrome::firm_name_from_context().await,
        csrf_token,
        role,
        notice: resolve_notice(query.notice.as_deref()),
    })
}

/// The lawyer cron-schedules page. Server-side rendered: each "Run now" is a
/// native `POST` carrying the CSRF token, so it works without JavaScript.
#[component]
pub fn LawyerSchedules() -> Element {
    let resource = use_server_future(get_schedules)?;

    let view = match &*resource.read() {
        Some(Ok(view)) => view.clone(),
        Some(Err(_)) => {
            return rsx! {
                main { id: "schedules", p { "Failed to load schedules." } }
            }
        }
        None => {
            return rsx! {
                main { id: "schedules", p { "Loading…" } }
            }
        }
    };

    schedules_body(&view)
}

/// The loaded page. Split from the component so the tests render a fixed view
/// without standing up the server function.
fn schedules_body(view: &SchedulesView) -> Element {
    let view = view.clone();
    let columns = vec![
        Column::fixed("job", "Job"),
        Column::fixed("schedule", "Schedule (UTC)"),
        Column::fixed("cadence", "Cadence"),
        Column::fixed("description", "What it does"),
        Column::fixed("run", "Run now"),
    ];

    rsx! {
        document::Title { "{view.firm_name} | Lawyer | Cron schedules" }
        document::Stylesheet { href: crate::components::THEME_STYLESHEET_HREF }
        document::Stylesheet { href: "{view.tokens_href}" }
        nav { class: "lawyer-nav",
            a { class: "nav-link", href: "/app/projects", "Portal" }
            if view.role.is_lawyer_tier() {
                a { class: "nav-link", href: "/app/lawyer", "Lawyer" }
            }
            if view.role.is_admin_tier() {
                a { class: "nav-link", href: "/app/admin", "Admin" }
            }
            a { class: "nav-link", href: "/auth/logout", "Sign out" }
        }
        main { id: "schedules", class: "nav-theme",
            if let Some(notice) = view.notice.as_ref() {
                Toast {
                    message: notice.message.clone(),
                    tone: if notice.queued { ToastTone::Success } else { ToastTone::Danger },
                }
            }
            header { class: "page-header",
                h1 { "Cron schedules" }
                p { class: "nav-muted",
                    "Scheduled jobs that run on the cluster, shown with the cron expression "
                    "(UTC) and the Pacific cadence. Run any job on demand here that starts a "
                    "durable workflow."
                }
            }
            DataTable {
                columns,
                sort: SortState::default(),
                base_path: SCHEDULES_PATH.to_string(),
                for job in cron_jobs() {
                    tr {
                        td { strong { "{job.name}" } }
                        td { code { "{job.schedule}" } }
                        td { "{job.cadence}" }
                        td { "{job.description}" }
                        td {
                            if let Some(action) = job.manual_run() {
                                form { method: "post", action: "{action}",
                                    input {
                                        r#type: "hidden",
                                        name: "_csrf",
                                        value: "{view.csrf_token}",
                                    }
                                    button {
                                        r#type: "submit",
                                        class: "nav-btn nav-btn--primary",
                                        "Run now"
                                    }
                                }
                            } else {
                                span { class: "nav-muted", "—" }
                            }
                        }
                    }
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;
    use std::path::{Path, PathBuf};

    use super::*;

    fn view() -> SchedulesView {
        SchedulesView {
            tokens_href: String::new(),
            firm_name: "Neon Law".to_string(),
            csrf_token: "tok-9".into(),
            role: ViewerRole::Lawyer,
            notice: None,
        }
    }

    /// The manifest directory `ops ship` embeds and renders.
    fn exports_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../examples/deploy/k8s/exports")
    }

    /// Read a manifest's `kind` and `metadata.name`, or `None` when it is not a
    /// `CronJob`.
    fn cron_job_name(path: &Path) -> Option<String> {
        let text = std::fs::read_to_string(path).expect("the manifest reads");
        let document: serde_yaml::Value = serde_yaml::from_str(&text).expect("the manifest parses");
        if document.get("kind").and_then(serde_yaml::Value::as_str) != Some("CronJob") {
            return None;
        }
        Some(
            document
                .get("metadata")
                .and_then(|metadata| metadata.get("name"))
                .and_then(serde_yaml::Value::as_str)
                .expect("a CronJob names itself")
                .to_string(),
        )
    }

    /// The `CronJob`s the deployment renders, re-derived here from the
    /// kustomization independently of `build.rs`, so a broken generator is a
    /// failure rather than a silently agreed-on wrong answer.
    fn rendered_cron_job_names() -> BTreeSet<String> {
        let exports = exports_dir();
        let text = std::fs::read_to_string(exports.join("kustomization.yaml"))
            .expect("the kustomization reads");
        let document: serde_yaml::Value =
            serde_yaml::from_str(&text).expect("the kustomization parses");
        document
            .get("resources")
            .and_then(serde_yaml::Value::as_sequence)
            .expect("the kustomization lists resources")
            .iter()
            .filter_map(|entry| cron_job_name(&exports.join(entry.as_str()?)))
            .collect()
    }

    /// Every `CronJob` manifest sitting in `exports/` that no `resources:` entry
    /// names, and which therefore renders nowhere.
    fn unrendered_cron_job_names() -> BTreeSet<String> {
        let rendered = rendered_cron_job_names();
        let mut unrendered = BTreeSet::new();
        for entry in std::fs::read_dir(exports_dir()).expect("the exports directory reads") {
            let path = entry.expect("the directory entry reads").path();
            if path.extension().is_none_or(|extension| extension != "yaml") {
                continue;
            }
            if let Some(name) = cron_job_name(&path) {
                if !rendered.contains(&name) {
                    unrendered.insert(name);
                }
            }
        }
        unrendered
    }

    #[test]
    fn the_console_lists_exactly_the_cron_jobs_the_deployment_renders() {
        // The page's whole contract. Written against the render rather than a
        // fixed set of names, so adding or removing a manifest from
        // `resources:` moves the page and leaves this test green.
        let rendered = rendered_cron_job_names();
        let listed: BTreeSet<String> = RENDERED_CRON_JOBS
            .iter()
            .map(|job| job.name.to_string())
            .collect();
        assert_eq!(
            listed, rendered,
            "the generated table and the kustomization disagree"
        );

        let html = dioxus_ssr::render_element(schedules_body(&view()));
        assert_eq!(
            cron_jobs().len(),
            rendered.len(),
            "the page renders {} rows for {} rendered CronJobs",
            cron_jobs().len(),
            rendered.len()
        );
        for job in cron_jobs() {
            assert!(
                html.contains(job.name),
                "{} renders but is missing from the page: {html}",
                job.name
            );
            assert!(
                html.contains(job.schedule),
                "{} renders without its schedule {}: {html}",
                job.name,
                job.schedule
            );
        }
    }

    #[test]
    fn a_manifest_the_render_leaves_out_never_reaches_the_console() {
        // A `.yaml` in `exports/` that no `resources:` entry names is applied to
        // no cluster, so the console must not advertise it as a schedule. Both
        // sides are derived, so adding one of these to `resources:` keeps this
        // green — it becomes a rendered job the test above then requires.
        let unrendered = unrendered_cron_job_names();
        let listed: BTreeSet<String> = RENDERED_CRON_JOBS
            .iter()
            .map(|job| job.name.to_string())
            .collect();
        for name in &unrendered {
            assert!(
                !listed.contains(name),
                "{name} is in no `resources:` list yet reaches the console"
            );
        }
    }

    #[test]
    fn every_rendered_cron_job_carries_operator_copy() {
        // The page never hides a rendered job, so a missing description shows
        // up here rather than as a row of placeholder text in production.
        for job in cron_jobs() {
            assert_ne!(
                job.description, UNDOCUMENTED,
                "CronJob/{} renders but has no JOB_COPY entry",
                job.name
            );
            assert!(!job.schedule.is_empty(), "{} missing schedule", job.name);
            assert!(!job.cadence.is_empty(), "{} missing cadence", job.name);
        }
    }

    #[test]
    fn copy_is_written_only_for_jobs_that_render() {
        // The mirror of the test above: prose left behind after a manifest
        // leaves `resources:` would otherwise sit here unnoticed.
        let rendered = rendered_cron_job_names();
        for copy in JOB_COPY {
            assert!(
                rendered.contains(copy.cron_name),
                "JOB_COPY describes {}, which the deployment does not render",
                copy.cron_name
            );
        }
    }

    #[test]
    fn lists_the_archives_export_with_schedule_and_trigger() {
        let html = dioxus_ssr::render_element(schedules_body(&view()));
        assert!(html.contains("Archives nightly export"), "{html}");
        assert!(html.contains("0 10 * * *"), "{html}");
        assert!(html.contains("02:00 PST"), "{html}");
        // The manual trigger renders as a CSRF-protected POST form.
        assert!(
            html.contains("action=\"/app/admin/schedules/archives/run\""),
            "{html}"
        );
        assert!(html.contains("name=\"_csrf\""), "{html}");
        assert!(html.contains("value=\"tok-9\""), "{html}");
        assert!(html.contains("Run now"), "{html}");
    }

    #[test]
    fn lists_the_billing_digest_daily_workflow() {
        let html = dioxus_ssr::render_element(schedules_body(&view()));
        assert!(html.contains("Billing digest"), "{html}");
        assert!(html.contains("0 13 * * *"), "{html}");
        assert!(html.contains("05:00 PST"), "{html}");
        assert!(html.contains("trailing-30-day GCP cost"), "{html}");
    }

    #[test]
    fn lists_the_durable_execution_heartbeat() {
        let html = dioxus_ssr::render_element(schedules_body(&view()));
        assert!(html.contains("Durable-execution heartbeat"), "{html}");
        assert!(html.contains("0 */6 * * *"), "{html}");
        assert!(html.contains("Every 6h"), "{html}");
        assert!(html.contains("Liveness canary"), "{html}");
    }

    #[test]
    fn a_job_with_no_durable_workflow_offers_no_run_now_button() {
        // A slug is what `portal::cron_schedules` dispatches on; a job it does
        // not know would answer 404, so the cell renders a dash instead.
        let batch = cron_jobs()
            .into_iter()
            .find(|job| job.slug.is_none())
            .expect("a rendered job runs its own batch");
        assert_eq!(batch.manual_run(), None);

        let html = dioxus_ssr::render_element(schedules_body(&view()));
        assert!(
            !html.contains(&format!("/app/admin/schedules/{}/run", batch.name)),
            "{html}"
        );
    }

    #[test]
    fn floats_a_queued_notice() {
        let html = dioxus_ssr::render_element(schedules_body(&SchedulesView {
            notice: resolve_notice(Some("queued:archives")),
            ..view()
        }));
        assert!(html.contains("Archives nightly export queued."), "{html}");
        assert!(html.contains("nav-toast--success"), "{html}");
    }

    #[test]
    fn floats_a_failure_notice() {
        let html = dioxus_ssr::render_element(schedules_body(&SchedulesView {
            notice: resolve_notice(Some("not_queued:heartbeat")),
            ..view()
        }));
        assert!(
            html.contains("Durable-execution heartbeat could not be queued."),
            "{html}"
        );
        assert!(html.contains("nav-toast--danger"), "{html}");
    }

    #[test]
    fn an_unknown_notice_resolves_to_nothing() {
        // The query is attacker-controlled, so only a known outcome+slug pair
        // renders — never the raw value.
        assert!(resolve_notice(None).is_none());
        assert!(resolve_notice(Some("queued:not-a-job")).is_none());
        assert!(resolve_notice(Some("exploded:archives")).is_none());
        assert!(resolve_notice(Some("no-colon")).is_none());
        assert!(resolve_notice(Some("<script>:archives")).is_none());
    }

    #[test]
    fn every_job_carries_a_schedule_cadence_and_slug() {
        for job in cron_jobs() {
            assert!(!job.schedule.is_empty(), "{} missing schedule", job.name);
            assert!(!job.cadence.is_empty(), "{} missing cadence", job.name);
            if let Some(slug) = job.slug {
                assert!(!slug.is_empty(), "{} carries an empty slug", job.name);
                assert_eq!(
                    job.manual_run(),
                    Some(format!("/app/admin/schedules/{slug}/run"))
                );
            }
        }
    }
}
