//! Derive the shipped `CronJob` set for the admin schedules console from the
//! deployment render.
//!
//! `webapp::schedules` renders the "Cron schedules" page. Its job list used to
//! be hand-written, and its comment claimed it mirrored the manifests under
//! `examples/deploy/k8s/exports/`. It mirrored the *directory*, and a directory
//! is not a render: `ops ship` applies `kubectl kustomize` over
//! `examples/deploy/k8s/gke`, whose root pulls in `../exports`, so the objects
//! that reach a cluster are exactly the ones that kustomization's `resources:`
//! list names. A `.yaml` file sitting in the directory and named by no
//! `resources:` list renders nowhere.
//!
//! Reading the same `resources:` list `kustomize` reads is what makes the page
//! follow the deployment instead of tracking it by hand: adding a manifest to
//! `resources:` adds its row with no Rust edit, and removing one removes the
//! row. That is the reasoning `cli::devx::ship`'s published-image preflight
//! already applies — it checks the *built manifest stream* rather than a
//! hard-coded list of image names, so a trigger added to `../exports` is
//! covered without touching the check.
//!
//! `exports/` is the whole production `CronJob` surface: no other tree the
//! render embeds (`examples/deploy/k8s/gke`, `k8s/base`, `k8s/components`)
//! carries a `CronJob`, and no patch or component adds or deletes one, so
//! resolving this one kustomization resolves every scheduled job that ships.
//!
//! Anything this script cannot account for fails the build rather than
//! resolving to a shorter list. A silently short list is the exact failure
//! being removed here, and a build error naming the entry is cheap to fix.

use std::{collections::BTreeSet, env, fmt::Write as _, fs, path::Path};

use serde_yaml::Value;

/// The kustomization whose `resources:` list decides which scheduled jobs ship.
const EXPORTS_DIR: &str = "../examples/deploy/k8s/exports";

fn main() {
    // Emitting any rerun-if directive opts out of Cargo's package-wide file
    // scan, so the manifest tree has to be named explicitly: the generated
    // table is stale the moment `resources:` or a `spec.schedule` changes, and
    // a stale table is the drift this whole script exists to prevent.
    println!("cargo:rerun-if-changed={EXPORTS_DIR}");
    println!("cargo:rerun-if-changed=build.rs");

    let exports = Path::new(EXPORTS_DIR);
    let rendered = rendered_cron_jobs(exports);

    let mut generated = String::from(
        "// @generated by webapp/build.rs from examples/deploy/k8s/exports/kustomization.yaml.\n\
         // Edit the manifests or that `resources:` list — never this table.\n\
         pub static RENDERED_CRON_JOBS: &[RenderedCronJob] = &[\n",
    );
    for (name, schedule) in &rendered {
        writeln!(
            generated,
            "    RenderedCronJob {{ name: {name:?}, schedule: {schedule:?} }},"
        )
        .expect("writing to a String cannot fail");
    }
    generated.push_str("];\n");

    let out = Path::new(&env::var("OUT_DIR").expect("OUT_DIR is set by cargo"))
        .join("rendered_cron_jobs.rs");
    fs::write(&out, generated).unwrap_or_else(|error| {
        panic!("writing {}: {error}", out.display());
    });
}

/// Every `CronJob` the exports kustomization renders, as `(name, schedule)`,
/// in `resources:` order.
fn rendered_cron_jobs(exports: &Path) -> Vec<(String, String)> {
    let kustomization = exports.join("kustomization.yaml");
    let resources = resource_list(&kustomization);

    // A name listed twice would render once but appear twice on the page.
    let mut seen = BTreeSet::new();
    let mut jobs = Vec::new();
    for resource in resources {
        let path = exports.join(&resource);
        // A directory entry (a nested kustomization) or a remote base is a shape
        // this derivation does not resolve. Failing here is the point: the
        // alternative is a scheduled job the console never mentions.
        assert!(
            path.is_file(),
            "{}: `resources:` entry {resource:?} is not a file in {}. The schedules \
             console derives its rows from this list, so teach webapp/build.rs to \
             resolve this entry rather than leaving the job off the page.",
            kustomization.display(),
            exports.display()
        );

        let text = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("reading {}: {error}", path.display()));
        let document: Value = serde_yaml::from_str(&text)
            .unwrap_or_else(|error| panic!("parsing {}: {error}", path.display()));

        // The list carries every kind the deployment ships, not only CronJobs
        // (`surreal-archive-monitoring.yaml` is a monitoring `Rules` object).
        if document.get("kind").and_then(Value::as_str) != Some("CronJob") {
            continue;
        }

        let name = document
            .get("metadata")
            .and_then(|metadata| metadata.get("name"))
            .and_then(Value::as_str)
            .unwrap_or_else(|| panic!("{}: CronJob has no metadata.name", path.display()));
        let schedule = document
            .get("spec")
            .and_then(|spec| spec.get("schedule"))
            .and_then(Value::as_str)
            .unwrap_or_else(|| panic!("{}: CronJob/{name} has no spec.schedule", path.display()));

        assert!(
            seen.insert(name.to_string()),
            "{}: CronJob/{name} is rendered by more than one `resources:` entry",
            kustomization.display()
        );
        jobs.push((name.to_string(), schedule.to_string()));
    }

    assert!(
        !jobs.is_empty(),
        "{}: no CronJob renders — the schedules console would be empty",
        kustomization.display()
    );
    jobs
}

/// The `resources:` list, in file order.
fn resource_list(kustomization: &Path) -> Vec<String> {
    let text = fs::read_to_string(kustomization)
        .unwrap_or_else(|error| panic!("reading {}: {error}", kustomization.display()));
    let document: Value = serde_yaml::from_str(&text)
        .unwrap_or_else(|error| panic!("parsing {}: {error}", kustomization.display()));

    document
        .get("resources")
        .and_then(Value::as_sequence)
        .unwrap_or_else(|| panic!("{}: no `resources:` sequence", kustomization.display()))
        .iter()
        .map(|entry| {
            entry
                .as_str()
                .unwrap_or_else(|| {
                    panic!(
                        "{}: `resources:` holds a non-string entry",
                        kustomization.display()
                    )
                })
                .to_string()
        })
        .collect()
}
