//! `navigator dev docs ...` — command-line access to published workspace docs.
//!
//! The glossary is the same vocabulary the website publishes at
//! `/documents/glossary`: parsed from `docs/glossary.md` by
//! [`store::glossary::parse`] so the CLI cannot drift from the page.

use std::process::ExitCode;

use store::glossary::{
    parse, with_rendered_index, Term, GLOSSARY_LABEL, GLOSSARY_MD, GLOSSARY_PATH,
};

use crate::palette;

#[must_use]
pub fn list() -> ExitCode {
    let docs = portal::docs::loader::bundled();
    for doc in docs.docs() {
        println!(
            "/documents/{slug}\t{title}",
            slug = doc.slug,
            title = doc.title
        );
    }
    for entry in glossary_entries() {
        println!(
            "/documents/glossary#{slug}\tGlossary: {title}",
            slug = entry.slug,
            title = entry.title,
        );
    }
    ExitCode::SUCCESS
}

#[must_use]
pub fn glossary(term: Option<&str>) -> ExitCode {
    let entries = glossary_entries();
    let Some(needle) = term else {
        for entry in &entries {
            print_entry(entry);
        }
        return ExitCode::SUCCESS;
    };
    if let Some(entry) = entries.iter().find(|entry| matches_entry(entry, needle)) {
        print_entry(entry);
        ExitCode::SUCCESS
    } else {
        eprintln!("navigator: docs glossary: unknown term `{needle}`");
        eprintln!("Run `navigator dev docs list` to list every published docs page.");
        ExitCode::from(1)
    }
}

fn print_entry(entry: &Term) {
    println!("## {}", palette::header(&entry.title));
    println!();
    println!("{}", entry.body.trim());
    println!();
}

fn matches_entry(entry: &Term, needle: &str) -> bool {
    entry.title.eq_ignore_ascii_case(needle) || entry.slug == store::glossary::slugify(needle)
}

/// Check — or with `write`, refresh — the alphabetical index block at
/// the top of the authored glossary.
///
/// The index is derived data: every entry is one of the page's own `## `
/// headings, linked by its published anchor. Deriving it here rather
/// than by hand is what keeps the two halves of a Notion round trip
/// honest, since both sides regenerate the same block from the same
/// headings instead of hand-editing a list of ninety-nine links.
///
/// The target is [`GLOSSARY_PATH`] and takes no flag. There is exactly
/// one authored glossary, the workspace gate compares the rendered index
/// against the copy [`GLOSSARY_MD`] embeds from that same path, and a
/// caller-supplied target could only disagree with the file the gate
/// reads.
#[must_use]
pub fn glossary_index(write: bool) -> ExitCode {
    let raw = match std::fs::read_to_string(GLOSSARY_PATH) {
        Ok(raw) => raw,
        Err(error) => {
            eprintln!("navigator: docs glossary-index: {GLOSSARY_LABEL}: {error}");
            return ExitCode::from(1);
        }
    };
    let Some(rendered) = with_rendered_index(&raw) else {
        eprintln!(
            "navigator: docs glossary-index: {GLOSSARY_LABEL} has no `{lead}` line to refresh",
            lead = store::glossary::INDEX_LEAD,
        );
        return ExitCode::from(1);
    };
    if rendered == raw {
        println!("{GLOSSARY_LABEL}: index is current");
        return ExitCode::SUCCESS;
    }
    if !write {
        eprintln!(
            "navigator: docs glossary-index: {GLOSSARY_LABEL} index is stale; \
             re-run with --write"
        );
        return ExitCode::from(1);
    }
    if let Err(error) = std::fs::write(GLOSSARY_PATH, rendered) {
        eprintln!("navigator: docs glossary-index: {GLOSSARY_LABEL}: {error}");
        return ExitCode::from(1);
    }
    println!("{GLOSSARY_LABEL}: index rewritten");
    ExitCode::SUCCESS
}

/// The public repository every rewritten source link points into.
const REPO: &str = cloud::workspace::NAVIGATOR_REPOSITORY_URL;

/// Print the authored glossary as Markdown a Notion page can hold.
///
/// Notion has no notion of this repository's working directory, so the
/// three link shapes `docs/glossary.md` uses have to be resolved before
/// the text leaves the tree:
///
/// - `../store/src/persons.rs` and `../store/` — repository-relative,
///   rewritten to a `blob`/`tree` URL on `main`.
/// - `notation.md#template` — a sibling doc, rewritten into `docs/`.
/// - `#participation` — an in-page anchor, which Notion cannot resolve
///   at all, so the link is dropped and its label kept. That is what
///   turns the alphabetical index into a plain list on the Notion side;
///   the index is derived data regenerated by
///   [`glossary_index`] on each end, never round-tripped by hand.
///
/// The frontmatter and the `# Glossary` H1 are dropped too: the page's
/// own title carries one and Notion has no use for the other.
#[must_use]
pub fn glossary_notion() -> ExitCode {
    print!("{}", notion_markdown(GLOSSARY_MD));
    ExitCode::SUCCESS
}

/// The provenance blockquote every push writes as the page's first
/// block, so a reader who arrives at the Notion copy first learns which
/// way the sync runs before they start typing into it.
fn notion_preface() -> String {
    format!(
        "> Generated from [`docs/glossary.md`]({REPO}/blob/main/docs/glossary.md) by \
         `navigator dev docs glossary-notion`. The repository is the source of truth: an edit made \
         here reaches the product only once it lands in that file through a pull request. In-page \
         anchors are dropped because Notion cannot resolve them, so the index below is a plain \
         list.\n\n"
    )
}

fn notion_markdown(raw: &str) -> String {
    let body = rules::frontmatter::split(raw).map_or(raw, |(_, body)| body);
    let mut kept = String::with_capacity(body.len());
    for line in body.lines() {
        // The page's own title carries the H1, and the blank lines that
        // led it would open the page with a gap.
        if line.starts_with("# ") || (kept.is_empty() && line.is_empty()) {
            continue;
        }
        kept.push_str(line);
        kept.push('\n');
    }
    format!(
        "{preface}{rewritten}",
        preface = notion_preface(),
        rewritten = unwrap_paragraphs(&rewrite_links(&kept))
    )
}

/// Undo the repository's 120-character hard wrap.
///
/// The wrap exists so a definition reviews cleanly in a diff; Notion
/// lays its own text out and renders every one of those newlines as a
/// break, which turns a paragraph into a ladder. Joining here is also
/// what makes the push idempotent: the Notion page then holds exactly
/// this command's output, so a later push can be compared against it
/// instead of guessed at.
///
/// Fenced code blocks, tables, and thematic breaks are copied verbatim —
/// their line structure is the content.
fn unwrap_paragraphs(markdown: &str) -> String {
    let mut out: Vec<String> = Vec::new();
    let mut fenced = false;
    for line in markdown.lines() {
        if line.trim_start().starts_with("```") {
            fenced = !fenced;
            out.push(line.to_string());
            continue;
        }
        if fenced {
            out.push(line.to_string());
            continue;
        }
        match out.last() {
            Some(previous) if continues(previous, line) => {
                let joined = format!(
                    "{previous} {next}",
                    previous = previous.trim_end(),
                    next = line.trim_start().trim_start_matches("> ")
                );
                let last = out.len() - 1;
                out[last] = joined;
            }
            _ => out.push(line.to_string()),
        }
    }
    let mut joined = out.join("\n");
    joined.push('\n');
    joined
}

/// Whether `line` is a soft-wrapped continuation of `previous`.
fn continues(previous: &str, line: &str) -> bool {
    if previous.trim().is_empty() || line.trim().is_empty() {
        return false;
    }
    // A block whose shape is its line structure never absorbs the line
    // beneath it.
    if previous.starts_with('#') || previous.starts_with('|') || previous.starts_with("---") {
        return false;
    }
    let opener = line.trim_start();
    if opener.starts_with('#')
        || opener.starts_with('|')
        || opener.starts_with("---")
        || opener.starts_with("- ")
        || opener.starts_with("* ")
        || opener
            .split_once(". ")
            .is_some_and(|(n, _)| !n.is_empty() && n.bytes().all(|b| b.is_ascii_digit()))
    {
        return false;
    }
    // A blockquote continues only another blockquote, and vice versa.
    previous.starts_with("> ") == opener.starts_with("> ")
}

/// Rewrite every `[label](destination)` in the document.
///
/// Whole-document rather than line-by-line: the source is hard-wrapped
/// at 120 characters, so a link label routinely straddles a newline
/// (`[Coverage\n  Finding](#coverage-finding)`) and a per-line scan
/// would strip the half that carries the destination.
///
/// Destinations in this document hold no parentheses, so the first `)`
/// after a `](` closes the link; a destination that ever grows one would
/// be left verbatim rather than mangled.
fn rewrite_links(line: &str) -> String {
    let mut out = String::with_capacity(line.len());
    let mut rest = line;
    while let Some(at) = rest.find("](") {
        let Some(close) = rest[at + 2..].find(')') else {
            break;
        };
        let dest = &rest[at + 2..at + 2 + close];
        let head = &rest[..at];
        rest = &rest[at + 2 + close + 1..];
        match notion_link(dest) {
            Some(resolved) => {
                out.push_str(head);
                out.push_str("](");
                out.push_str(&resolved);
                out.push(')');
            }
            // An in-page anchor: drop the brackets, keep the label.
            None => match head.rfind('[') {
                Some(open) => {
                    out.push_str(&head[..open]);
                    out.push_str(&head[open + 1..]);
                }
                None => out.push_str(head),
            },
        }
    }
    out.push_str(rest);
    out
}

/// Resolve one link destination, or `None` for an in-page anchor.
fn notion_link(dest: &str) -> Option<String> {
    if dest.starts_with("http://") || dest.starts_with("https://") || dest.starts_with("mailto:") {
        return Some(dest.to_string());
    }
    let (path, anchor) = dest
        .split_once('#')
        .map_or((dest, None), |(p, a)| (p, Some(a)));
    if path.is_empty() {
        return None;
    }
    let repo_path = match path.strip_prefix("../") {
        Some(up) if !up.is_empty() && !up.starts_with("../") && !up.starts_with('/') => {
            up.to_string()
        }
        Some(_) => return Some(dest.to_string()),
        None => format!("docs/{path}"),
    };
    let kind = if repo_path.ends_with('/') {
        "tree"
    } else {
        "blob"
    };
    let url = format!(
        "{REPO}/{kind}/main/{path}",
        path = repo_path.trim_end_matches('/')
    );
    Some(match anchor {
        Some(a) => format!("{url}#{a}"),
        None => url,
    })
}

fn glossary_entries() -> Vec<Term> {
    parse(GLOSSARY_MD)
}

#[cfg(test)]
mod tests {
    use super::glossary_entries;
    use store::glossary::GLOSSARY_MD;

    #[test]
    fn parses_glossary_headings_as_entries() {
        let entries = glossary_entries();
        assert!(entries.iter().any(|entry| entry.title == "Project"));
        assert!(entries.iter().any(|entry| entry.title == "Lawyer Review"));
    }

    #[test]
    fn heading_slug_matches_published_docs_anchor_shape() {
        assert_eq!(store::glossary::slugify("Lawyer Review"), "lawyer-review");
        assert_eq!(
            store::glossary::slugify("Engagement / Retainer"),
            "engagement--retainer"
        );
    }

    #[test]
    fn glossary_headings_are_alphabetical() {
        let headings = GLOSSARY_MD
            .lines()
            .filter_map(|line| line.strip_prefix("## "))
            .map(|heading| heading.trim().trim_matches('`'))
            .collect::<Vec<_>>();
        let mut alphabetical = headings.clone();
        alphabetical.sort_by_key(|heading| heading.to_lowercase());

        assert_eq!(
            headings, alphabetical,
            "glossary headings must be alphabetical"
        );
    }

    #[test]
    fn notion_markdown_resolves_every_link_shape() {
        let rendered = super::notion_markdown(GLOSSARY_MD);
        assert!(
            !rendered.contains("publish: true"),
            "the publish frontmatter must not reach Notion"
        );
        assert!(
            rendered.starts_with("> Generated from [`docs/glossary.md`]"),
            "the page must open with its provenance"
        );
        assert!(
            rendered.contains(
                "A postal address attached to a Person, to an Entity, or to neither (the \
                 mailroom placeholder). The person/entity exclusivity is enforced by the \
                 application, not the schema."
            ),
            "a hard-wrapped paragraph must reach Notion as one line"
        );
        assert!(
            !rendered.contains("\n# Glossary"),
            "the Notion page title carries the H1"
        );
        assert!(
            !rendered.contains("](../"),
            "a repository-relative link cannot resolve from Notion"
        );
        assert!(
            !rendered.contains("](#"),
            "an in-page anchor cannot resolve from Notion"
        );
        assert!(
            !rendered.contains("](erd.md"),
            "a sibling doc link cannot resolve from Notion"
        );
        assert!(rendered.contains(&format!(
            "({repo}/blob/main/store/src/persons.rs)",
            repo = super::REPO
        )));
        assert!(rendered.contains(&format!("({repo}/tree/main/store)", repo = super::REPO)));
        assert!(rendered.contains(&format!(
            "({repo}/blob/main/docs/erd.md#schema)",
            repo = super::REPO
        )));
    }

    #[test]
    fn an_unlinked_index_entry_keeps_its_label() {
        assert_eq!(
            super::rewrite_links("- **A** \u{2014} [Asset](#asset) \u{b7} [Address](#address)"),
            "- **A** \u{2014} Asset \u{b7} Address"
        );
    }

    #[test]
    fn the_committed_index_is_what_the_renderer_produces() {
        assert_eq!(
            store::glossary::with_rendered_index(GLOSSARY_MD).as_deref(),
            Some(GLOSSARY_MD),
            "docs/glossary.md index is stale \u{2014} run \
             `cargo run -p cli -- dev docs glossary-index --write`"
        );
    }

    #[test]
    fn every_index_entry_links_a_real_heading() {
        let slugs: Vec<String> = glossary_entries()
            .iter()
            .map(|entry| entry.slug.clone())
            .collect();
        // The frontmatter fence is also a `---` line, so the preamble is
        // isolated from the body rather than from the raw file.
        let body = rules::frontmatter::split(GLOSSARY_MD).map_or(GLOSSARY_MD, |(_, body)| body);
        let index = body
            .split("\n---\n")
            .next()
            .expect("the preamble precedes the first term");
        for slug in &slugs {
            assert!(
                index.contains(&format!("(#{slug})")),
                "the alphabetical index is missing `{slug}`"
            );
        }
        assert!(
            !index.contains("## "),
            "the index must stay in the preamble so `store::glossary::parse` \
             never reads a letter group as a term"
        );
    }

    #[test]
    fn glossary_terms_match_the_published_docs_page() {
        let entries = glossary_entries();
        let docs = portal::docs::loader::bundled();
        let glossary = docs
            .find("glossary")
            .expect("glossary is published at /documents/glossary");
        assert!(
            !entries.is_empty(),
            "the CLI glossary must parse the authored vocabulary"
        );
        let mut html_ids = Vec::new();
        let mut rest = glossary.body_html.as_str();
        while let Some(at) = rest.find("<h2 id=\"") {
            rest = &rest[at + 8..];
            let Some(end) = rest.find('"') else {
                break;
            };
            html_ids.push(rest[..end].to_string());
            rest = &rest[end + 1..];
        }
        let slugs: Vec<String> = entries.iter().map(|entry| entry.slug.clone()).collect();
        assert_eq!(
            slugs, html_ids,
            "navigator dev docs glossary drifted from /documents/glossary"
        );
        for entry in &entries {
            assert!(
                glossary
                    .body_html
                    .contains(&format!("<h2 id=\"{}\">", entry.slug)),
                "published /documents/glossary missing heading for `{}`",
                entry.title
            );
        }
    }

    #[test]
    fn docs_list_includes_the_glossary_page_from_the_bundled_index() {
        let docs = portal::docs::loader::bundled();
        assert!(
            docs.docs().iter().any(|doc| doc.slug == "glossary"),
            "the published docs index must include /documents/glossary"
        );
        assert_eq!(
            docs.find("glossary").map(|doc| doc.title.as_str()),
            Some("Glossary")
        );
    }
}
